# Generated by Django 4.0.2 on 2022-03-06 19:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'Processing'), ('AP', 'Available for Pick-Up'), ('OD', 'Out for Delivery'), ('UC', 'Unfulfilled and Closed'), ('FC', 'Fulfilled and Closed')], default='N', max_length=2)),
            ],
        ),
    ]
